/**
 * MẸO CHO BỐ MẸ — mỗi tuần một điều cần để ý (dành cho phụ huynh không học nhạc).
 * Hiện ở màn chính (dòng nhỏ) và màn Phụ huynh. v5 (OWNER duyệt 2026-10-05): 30 tuần; v5.1 (2026-10-06): 31 tuần — tách tuần 18, thêm tuần 19 nghịch phách. Cấp 4 (2026-10-08): tuần 32–43 + PHIẾU XEM TAY (vai · khớp ngón · cổ tay).
 * (2026-10-08, OWNER duyệt) lời dẫn cho bé rút ngắn (≤ ~12 chữ) — chi tiết cho người lớn (thế tay, nguồn bài, nhịp lấy đà…) chuyển vào đây.
 */
export const PARENT_TIPS: Record<number, string> = {
  1: 'Cho bé tự tìm phím, đừng chỉ hộ. Khen khi bé nói được "Đô ở bên trái hai phím đen". Bài thử thách cho phép trượt 1 lần — đừng bắt làm lại từ đầu. Buổi đầu tiên chỉ 1 thẻ tư thế để bé chạm đàn thật ngay — từ buổi 2 mới đủ 3 thẻ.',
  2: 'Để ý ngón: Đô = ngón cái, Rê = ngón trỏ, Mi = ngón giữa. Khi không bật micro, phiếu chấm có 3 ý (đúng nốt · đều nhịp · đúng ngón) — chỉ đánh "đạt" khi cả 3 đều đạt. Tiêu chí tuần cần đạt ở 2 NGÀY khác nhau.',
  3: 'Ngón 4 và 5 thường yếu và hay "gập" — nhắc bé giữ ngón cong như ôm quả bóng nhỏ. Trò phím đen: không có nốt sai, cứ để bé tự do. Trò tai nghe chỉ 6 lượt: đúng 5/6 trong một buổi, ở 2 ngày khác nhau là đạt — sai 1 câu vẫn qua, đừng nhắc bài hộ.',
  4: 'Đếm to cùng bé "1-2-3-4". Đều quan trọng hơn nhanh: cho bé đàn chậm (tốc độ 40) trước. "Chạy-chạy" = hai nốt nhanh đều nhau trong một phách. Nốt tròn "Đi-i-i-i" giữ đủ 4 phách. Từ tuần này lượt THEO NHỊP của bài đã quen chỉ hiện tên nốt (phím không sáng) — đừng bật lại phím sáng, để bé nhìn khuông. Trò phím đen cuối tuần: không có nốt sai.',
  5: 'Tuần củng cố: không có gì mới — bé đàn bài mới bằng kỹ năng cũ. Đây là lúc bé thấy mình "giỏi lên". Khen sự tự tin, đừng vội chuyển tuần. Trò "Đàn liền": nốt trước chỉ nhả khi nốt sau đã vang — như nước chảy, không hở (ngắt tiếng học sau, ở tuần 12).',
  6: 'Tập từng câu, chỉ ghép cả bài khi từng câu đã trơn. Bật nhạc đệm để bé thấy vui. Trò "To hay nhỏ?": f = to (ấn sâu, ngón chắc), p = nhỏ (chạm nhẹ) — đàn nhỏ KHÔNG có nghĩa là đàn chậm. "Bài ca niềm vui" của Beethoven; "Các thánh tiến bước" có một nốt Đô giữ 3 phách. Trò Hỏi – Đáp: app hỏi TO, bé trả lời NHỎ — câu nào kết ở Đô cũng đúng.',
  7: 'Tay trái thường lười hơn: chỉ cần 3–5 phút/buổi. Khen nhiều khi bé không nhìn tay. Tai nghe nốt trầm: 6 lượt, đúng 5/6 ở 2 ngày là đạt. Thấy dấu p/f trong bài, hỏi bé "chỗ này to hay nhỏ?" trước khi đàn. Khúc Largo (Dvořák) có dấu luyến cong: đàn LIỀN như trò "Đàn liền" tuần 5.',
  8: 'Bé đọc khuông thì dễ nhìn tay. Che nhẹ bàn tay bé bằng một tờ giấy để bé nhìn khuông. Hỏi "nốt mốc gần nhất là nốt nào?" thay vì đọc hộ. Nốt La: khi Sol–La đi cùng nhau, Sol ngón 4, La ngón 5. "Kìa con bướm vàng": câu cuối ngón 1 với xuống Sol trầm. Hai nốt trên khuông: cùng chỗ = giống, vạch/khe ngay cạnh = bước, cách một = nhảy.',
  9: 'Nhịp 2/4: mỗi ô chỉ 2 phách "MỘT-hai". Cùng bé vỗ tay hát "Inh lả ơi" trước khi đàn. Trò Hỏi – Đáp: mọi câu trả lời kết ở Đô đều đúng. "Inh lả ơi" (dân ca Thái Tây Bắc): ngón cái ở Rê. "Xòe hoa" (điệu múa xòe Thái) bắt đầu bằng một nốt Đô lấy đà; tay ngũ cung Đô 1 – Rê 2 – Fa 3 – Sol 4 – La 5. "Trống trường" theo nhịp chỉ nhìn khuông — đừng đọc hộ tên nốt.',
  10: 'Buổi biểu diễn: cả nhà ngồi nghe, vỗ tay to. Đừng sửa lỗi lúc bé đang đàn. Bài "Bánh nóng — thế Sol" là xem trước thế tay của tuần 14 (ngón cái ở Sol). "Gà gáy" là dân ca Cống (Lai Châu), tay đặt Rê 1 – Mi 2 – Sol 3 – La 4 – Si 5.',
  11: 'Khóa Fa mới lạ — đọc to tên nốt cùng bé, bắt đầu từ nốt mốc Fa (vạch giữa hai dấu chấm). Hai tay luân phiên: chờ tay này xong tay kia mới vào. Bài cuối tuần là lần đầu gặp NHỊP 3 "MỘT-hai-ba" (nốt trắng chấm "Đi-i-i" = 3 phách) — cùng bé đung đưa người theo nhịp.',
  12: 'Hai tay cùng lúc rất khó: bài đầu tuần có sẵn bước tập riêng tay phải, rồi tay trái ở CÂU KHÓ nhất (không phải cả bài), rồi mới ghép hai tay cả bài — ghép ở tốc độ 40. Ngắt (dấu chấm) = nhấc ngón ngay như chạm bếp nóng; liền (dấu luyến cong) = nốt trước chỉ nhả khi nốt sau đã vang.',
  13: 'Tuần củng cố hai tay: bài mới nhưng kỹ năng cũ. Khi bé sáng tác, đừng sửa "cho hay" — hỏi bé "bài này kể chuyện gì?". "Lý cây xanh" (dân ca Nam Bộ, 2/4): tay phải Mi 1 – Sol 2 – La 3 – Đô cao 5; tay trái chỉ Rê (ngón cái) và Đô (ngón 2).',
  14: 'Khi đổi sang thế Sol, nhắc bé "ngón cái về nhà mới ở Sol" trước khi bắt đầu.',
  15: 'Nhịp 3 (đã gặp ở tuần 11): bé hay đếm thành 4. Cùng bé đung đưa người "MỘT-hai-ba". Hai bài valse thế Đô: lượt theo nhịp chỉ nhìn khuông. "Chúc mừng sinh nhật" bắt đầu ở phách 3 (hai nốt lấy đà).',
  16: 'Phím đen: bé hay quên dấu ♯ ở giữa bài. Trước khi đàn, hỏi bé "Bài này có phím đen nào?". "Kìa con bướm vàng — giọng buồn" có thêm La GIÁNG ở câu 3: tay nhích lên, Sol ngón 4 – La giáng ngón 5.',
  17: 'Nốt chấm dôi: cho bé nói "Đi-chấm chạy" trước khi đàn. Nghe mẫu nhiều lần là cách tốt nhất. Khởi động "cá lặn" (luồn ngón cái) là chuẩn bị cho gam ở tuần 20.',
  18: 'Móc kép rất nhanh: bài bắt đầu ở tốc độ 40 là đúng. Cho bé đọc to "Chạy-chạy-chạy-chạy" rồi mới đàn. "Tập-tễnh" (móc đơn chấm + móc kép): như đi cà nhắc — dài rồi ngắn. "Lý cây đa" là dân ca quan họ Bắc Ninh; ô đầu có dấu lặng trước nốt Đô.',
  19: 'Nghịch phách "Chạy-Đi-chạy": cùng bé vỗ tay và nói to trước khi đàn — nốt "Đi" vang ở chữ "và", lệch phách mới đúng. Dấu nối: chỉ vỗ MỘT lần cho cả hai nốt. Nghe mẫu nhiều lần. "Bắc kim thang" (dân ca Nam Bộ): bàn tay ngũ cung Đô 1 – Rê 2 – Fa 3 – Sol 4 – La 5.',
  20: 'Luồn ngón cái phải nhẹ, không xoay cả cổ tay. Tập chậm, mỗi tay riêng. "Cò lả" (dân ca Bắc Bộ) có nhiều "Tập-tễnh": tay phải thế Đô (Đô 1, Rê 2, Mi 3, Sol 5), hai nốt Sol trầm là ngón cái tay trái.',
  21: 'Hòa nhạc Cấp 2: có thể quay video bằng điện thoại của bố mẹ để bé xem lại và tự hào.',
  22: 'Hợp âm: 3 ngón xuống CÙNG LÚC. Bé hay bấm lệch — cho bé đếm "1-2-3 bấm!".',
  23: 'Dòng kẻ phụ: bé đọc sai thì hỏi "từ Đô giữa đi xuống mấy bậc?" thay vì nói tên nốt. Khuông lớn: tay phải đọc khóa Sol, tay trái đọc khóa Fa. Trò đọc nốt 6 lượt: đúng 5/6 ở 2 ngày là đạt. Đô giữa của khóa Fa và khóa Sol là CÙNG một phím.',
  24: 'Đổi thế tay giữa bài: cho bé đánh dấu bằng bút chì chỗ phải dời tay (trong đầu) và tập riêng chỗ đó. "Lý ngựa ô" (dân ca Nam Bộ, bản đầy đủ): tay phải thế Sol (Sol 1, La 2, Si 3, Rê cao 5), tay trái Mi 1 – Rê 2 – Đô 3 – La trầm 5; đoạn cuối nhắc lại một lần.',
  25: 'Hỏi bé "bài này nghe vui hay buồn?" khi nghe nhạc ở nhà — luyện tai tự nhiên nhất. Trò "Vui hay buồn?" 6 lượt: đúng 5/6 ở 2 ngày là đạt.',
  26: 'Tuần đọc nốt cao: mỗi lần bé đọc sai, hỏi "nốt này ngồi ở vạch hay ở khe?" rồi đếm từ Đô cao (khe 3) lên. Không cần nhanh — đọc ĐÚNG trước. Thế Đô cao: ngón cái ở Đô cao, ngón 5 ở Sol cao (ngồi trên đỉnh khuông).',
  27: 'Đọc nhạc: đừng cho bé đoán. Mỗi nốt bé nói tên trước rồi mới đàn. "Lý cây bông" (dân ca Nam Bộ) đi từ khóa Sol xuống khóa Fa — hai tay thay nhau, không đàn cùng lúc.',
  28: 'Bài hai tay dài: app cho tập riêng từng tay ở câu khó nhất trước, rồi ghép hai tay cả bài. Ở nhà có thể chia đôi, mỗi buổi tập kỹ một nửa.',
  29: 'Minuet là nhạc cổ: tìm cho bé nghe bản gốc trên đài/TV nếu có dịp (không cần trong app). Tập từng câu, mỗi câu 3 lần đúng liền mới ghép. Bốn móc đơn dưới dấu luyến đàn LIỀN; hai nốt Sol có chấm đàn NGẮT.',
  30: 'Für Elise có Rê thăng: bé hay đánh Rê trắng. Tập riêng 5 nốt đầu thật nhiều lần. Bài khởi động "Mưa rào mùa hạ": Rê thăng là ngón 4.',
  31: 'Đại hòa nhạc — bé đã đi một chặng dài 31 tuần (≈ hết Faber cấp 1 / đầu cấp 2)! Tiếp tục 4–5 buổi ngắn mỗi tuần — sau buổi hòa nhạc là CẤP 4 (gam, hợp âm rải, pedal, 6/8); nếu có thể, tìm thêm một thầy/cô dạy trực tiếp.',
  32: 'CẤP 4 bắt đầu. PHIẾU XEM TAY (mỗi tuần Cấp 4, bé đàn câu đầu bài của tuần, bố mẹ chạm "Đúng rồi" từng ý): ① vai thả lỏng — không nhô lên, khuỷu tay không ép sát người; ② khớp đầu ngón KHÔNG gãy — đầu ngón đứng trên phím, khớp ngoài cùng không bẹp/cong ngược vào trong (hay gặp ở ngón 1 và ngón 5); ③ cổ tay mềm, ngang phím — không gồng, không võng xuống. Thấy gồng: dừng, thả rơi cánh tay 2 lần rồi đàn chậm lại. Gam Sol trưởng: tay phải luồn ngón cái xuống Đô (sau ngón 3), xuống gam ngón 3 vắt qua về Si; tay trái ngược lại. Nhớ Fa THĂNG. Cổ tay đi ngang, không xoay lật.',
  33: 'Gam Fa trưởng tay phải KHÁC các gam khác: 1-2-3-4 (ngón 4 ở Si giáng) rồi ngón cái luồn xuống Đô. Bé hay dùng ngón 3 cho Si giáng — nhắc nhẹ. Tay trái giống gam Đô (5-4-3-2-1 rồi 3 vắt qua), Si giáng là ngón 2. Phiếu xem tay: để ý khớp đầu ngón 4 — ngón yếu hay bẹp.',
  34: 'Gam hai tay cùng lúc rất khó vì mỗi tay luồn ngón ở chỗ khác nhau (tay phải ở nốt thứ 4, tay trái ở nốt thứ 6). Bài đầu tuần đã tách tay sẵn: tập chậm (tốc độ 40), đúng ngón trước rồi mới nhanh. Gam Rê trưởng có hai phím đen Fa thăng, Đô thăng. Vai hay nhô lên khi bé cố gắng — nhắc "thả vai".',
  35: 'Hợp âm rải: các ngón đi từng nốt nhưng bàn tay vẫn giữ dáng "ôm bóng" của hợp âm — không duỗi thẳng ngón. Rải đều, không vội ở nốt trên cùng. Hợp âm Fa (IV) rải Đô–Fa–La bằng 1-3-5 là tay mở rộng (quãng 6): nếu tay bé căng, cho bé xoay cổ tay nhẹ sang phải thay vì kéo ngón.',
  36: 'Bass Alberti (thấp – cao – giữa – cao): tay trái giữ yên, cổ tay LẮC nhẹ trái–phải như vẫy, ngón cái không dập mạnh — tay trái phải NHỎ hơn tay phải (giai điệu là chính). Sonatina: tay phải dời thế ở ô 5 (ngón 3 lên Fa) và về thế Đô ở ô 7. Bài "phong cách Clementi" là bài tự sáng tác cho app, không phải bản gốc của Clementi.',
  37: 'Tuần củng cố: không có gì mới. Minuet nhỏ Fa trưởng nhịp 3 — bé dễ dồn nhịp ở nốt trắng chấm cuối câu: đếm to "MỘT-hai-ba". Nếu tay bé mỏi khi tập gam hai tay, chia 2 buổi ngắn thay vì một buổi dài.',
  38: 'PEDAL (bàn đạp PHẢI): gót chân đặt trên sàn, chỉ mũi chân nhấn — không nhấc cả chân. "Nhả trước — nhấn sau": khi hợp âm MỚI vang lên thì nhả, rồi nhấn lại NGAY sau đó (đổi mỗi ô nhịp trong bài). Micro KHÔNG nghe được pedal — bố mẹ nghe: tiếng nhòe vào nhau (hợp âm cũ còn kêu trong hợp âm mới) là đổi muộn; có khoảng "hụt" tiếng là nhấn sớm. Chạm "Pedal sạch" chỉ khi đổi đúng cả bài. Nếu chân bé chưa chạm tới bàn đạp, kê một hộp/ghế đẩu nhỏ dưới chân trái và để bé ngồi sát mép ghế hơn — hoặc bỏ pedal, chỉ đàn tay.',
  39: 'Nhịp 6/8: mỗi ô có 6 móc đơn chia hai nhóm ba "MỘT-hai-ba BỐN-năm-sáu" — nhấn nhẹ ở 1 và 4, như đung đưa thuyền. App gõ 6 tiếng tích mỗi ô (mỗi tiếng là MỘT MÓC ĐƠN, nên "tốc độ 60" ở bài 6/8 là 60 móc đơn/phút — chậm hơn bài 4/4, đúng ý). Nốt đen + móc đơn = "dài – ngắn". "Row, row, row your boat" là bài hát thiếu nhi Mỹ thế kỷ 19.',
  40: 'Hai "mỏ" trên khuông: < (crescendo) = TO DẦN, > (diminuendo) = NHỎ DẦN — tăng/giảm từ từ qua nhiều nốt, không nhảy một lần. Andante = thong thả như đi bộ; Allegro = nhanh, vui; rit. = chậm dần ở cuối bài (app vẫn gõ nhịp đều — bé chỉ cần "thả" chậm một chút khi đàn cùng bố mẹ, micro không trừ điểm). Micro chưa chấm được to dần – nhỏ dần trong bài: bố mẹ nghe và chạm thẻ "To dần – nhỏ dần".',
  41: 'Gam La thứ "tự nhiên" toàn phím trắng (từ La tới La); gam "hòa âm" nâng nốt Sol thành Sol THĂNG — nghe "Ả Rập" hơn. Ngón giống gam Đô. Korobeiniki là dân ca Nga (giai điệu trò chơi "Tetris" quen thuộc): tay phải dời thế 3 lần ở câu 2: ô 5 ngón cái lên Rê cao trong dấu lặng; ô 6 ngón cái với xuống Đô cao sau nốt Mi dài; ô 7 ngón 2 bước qua ngón cái về Si. Tập riêng từng chỗ dời tay, nhìn trước nốt kế.',
  42: 'Tuần tập dượt cho hòa nhạc: cùng bé chọn 2–3 bài thích nhất (có thể một bài có pedal, một bài 6/8). Greensleeves là dân ca Anh (thế kỷ 16) nhịp 6/8, có Sol thăng (cả hai câu) và Fa thăng (câu cuối), chậm dần (rit.) ở cuối. Ngón tay đã soạn để bàn tay "bò" theo giai điệu: chỉ có một lần ngón cái nhảy Mi → La ở nốt lấy đà câu 2, và một lần nhích tay ở ô 7 (Fa thăng ngón 1). Làm phiếu xem tay thật kỹ: buổi hòa nhạc dễ làm bé gồng vai.',
  43: 'Đại hòa nhạc Cấp 4 — bé đã học xong gam trưởng/thứ, hợp âm rải, Alberti, pedal, 6/8 (≈ ABRSM Initial / đầu Grade 1). Sau đây "Luyện tập mỗi ngày" tiếp tục ôn; nếu có thể, đây là lúc tốt để tìm một thầy/cô dạy trực tiếp (kỹ thuật pedal và độ thả lỏng cần mắt người thật).',
};

export function parentTip(week: number): string {
  return PARENT_TIPS[week] ?? PARENT_TIPS[43];
}
